name: hive_cookie_store
description: >-
  A cookie store implementation for the cookie_jar package that uses Hive for
  persistence and encryption.
version: 0.1.0
homepage: https://github.com/furkankurt/hive_cookie_store
repository: https://github.com/furkankurt/hive_cookie_store
issue_tracker: https://github.com/furkankurt/hive_cookie_store/issues

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  cookie_jar: ^4.0.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path: ^1.9.0
  very_good_analysis: ">=6.0.0 <8.0.0"
